### ISSUE TITLE
Add first-class proxied SSH install support to Ranchhand

### ISSUE THREAD

**Issue by bstrand-ddl** [dominodatalab/ranchhand#23]
Proxied-through-SSH installation is currently handled in downstream shell scripts by rsync-ing ranchhand onto the bastion server before execution. It’d be nice to have first-class support for installation through an SSH bastion.

**Comment by sonnysideup** [comment]
Just to add a little more context:

https://github.com/dominodatalab/ranchhand/blob/9540ee100c0a19bbaaaea303b9edfd608030b786/pkg/ranchhand/run.go#L36

The entrypoint function coordinates the steps required to convert a a group of VMs into a Rancher HA cluster. `rke` already has proxy support so the bulk of the work really entails:

- add/change CLI flags as required
- provide RKE with the correct configuration
- ensure that host processing, Helm operations and Rancher comms function through a proxy host

**Comment by zs-ddl** [comment]
I have some thoughts with regards to this overall approach but I want to spend a little more time investigating before I give some suggestions (or create a PR). 

Thanks @sonnysideup for providing me with some context around RanchHand.

**Comment by zs-ddl** [comment]
I'd like to start a design discussion around RanchHand that is inspired by this feature request.

After some thought, I think it may be good to consider an alternative design (or strategy) to the cluster configuration management that RanchHand provides. My high-level design goals and concerns are as follows:

- [ ] Configuration as Code; Not Code as Configuration
- Often it's considered an antipattern to embed configuration within code. In our RanchHand case, we're embedding a lot of bash commands within the Golang binary.
- [ ] OSS Configuration Management (CM) Tools Already Exist
- There are already a lot of CM tools that provide the functionality we're trying to implement here: [Ansible](https://docs.ansible.com/ansible/latest/index.html), [Salt](https://docs.saltstack.com/en/latest/topics/), etc.

If I were to implement this as a Greenfield project, I'd use [Ansible](https://docs.ansible.com/ansible/latest/index.html). (Since ssh is Ansible's machine-to-machine transport mechanism, support for Bastion proxies is natively supported). But given the existing use of Salt within our deployment strategy, despite its complications, Salt may be the best tool moving forward. Both of these solutions are extensible and easily architect-out the bastion installation issue. 

I currently struggle to find a strong reason to maintain RanchHand in favor of its deprecation.

FYI @sonnysideup @steved @Secretions @bstrand-ddl

**Comment by zs-ddl** [comment]
Created a PR that addresses this issue natively via Ansible: https://github.com/dominodatalab/ranchhand/pull/30
